Fix for Error: ENOENT: no such file or directory
The latest two tests for the `contextVariables.json` was throwing:
Error: ENOENT: no such file or directory, open 'dist/data/mock-repository/contracts/full_match/0/0xE091184B7b0688cBD856435013eE20E5826d7Bd0

Upon debugging it turns out this was caused by
`process.env.MOCK_REPOSITORY` not being set by the `server.js`.
Because test `monitor.js` runs before `server.js` it runs
`config.ts` and the `repository.path` gets evaluated.
When the `server.js` runs it, it's value was already set and chaning
the env var does not take effect.

TODO: Remove the `config.ts` and assign variables without config,
but with env vars directly